#!/bin/sh

testdir=tests

style_print() {
	style=$1
	shift
	message=$*
	printf "\e[${style}m${message}\e[0m\n"
}

run_test() {
	testfile=$1
	log="${testfile}.log"
	style_print 31 "$testfile failure:" > $log
	./$testfile 2>>$log >/dev/null
	if [ $? -eq 0 ]; then
		style_print 32 $testfile succeeded.
		rm $log
	else
		style_print 31 $testfile failed.
	fi
}

cd $testdir

testfiles=`ls -1 | grep '\.o$'`


for testfile in $testfiles; do
	run_test $testfile &
done
wait

logs=`ls | grep '\.log$'`
if [ "$logs" ]; then
	style_print "31;7" Some tests failed.
	for log in $logs; do
		cat $log
	done
else
	style_print "32;7" All tests passed.
fi
