#!/bin/sh

library=$1
testdir=tests

is_tty() {
	[ -t 1 ]
}

style_print() {
	style=$1
	shift
	message=$*
	if is_tty; then
		printf "\e[%sm%s\e[0m\n" "$style" "$message"
	else
		printf "%s\n" "$message"
	fi
}

run_test() {
	testfile=$1
	log="${testfile}.log"
	style_print 31 "$testfile failure:" > "$log"
	if "./$testfile" 2>>"$log" >/dev/null; then
		style_print 32 "$testfile succeeded."
		rm "$log"
	else
		style_print 31 "$testfile failed."
	fi
}

cd "$testdir" || exit $?

ln -f "../$library" .
for testfile in *.test; do
	run_test "$testfile" &
done
wait
rm -f "$library"

if ! ls ./*.log 2>/dev/null >/dev/null; then
	style_print "32;7" All tests passed.
	exit 0
fi
style_print "31;7" Some tests failed.
for log in *.log; do
	cat "$log"
done
exit 1
